[package]
name = "confindent"
version = "1.1.1"
description = "⚙️ A configuration format based on indentation"
authors = ["genuinebyte <bja@genuinebyte.com>"]
repository = "https://git.sr.ht/~genbyte/confindent"
readme = "README.md"
keywords = ["config", "indentation"]
categories = ["config"]
license = "ISC"
edition = "2018"

[dependencies]


[[example]]
name = "read"

[[example]]
name = "write"
